# Support BuyMeACoffee.js by using the funding links below
# Developed and Maintained by Waren Gonzaga

issuehunt: WarenGonzaga/buymeacoffee.js
custom: ['https://bmc.xyz/warengonzaga','https://paypal.me/warengonzagaofficial']
